apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: akash-personal-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
